// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZBLFJrtNGMaHQLEa0uAsD25gsO1WW0ks',
    appId: '1:124678530522:web:82e6f2c8f5e135dcc04ce3',
    messagingSenderId: '124678530522',
    projectId: 'herfa-3e5ff',
    authDomain: 'herfa-3e5ff.firebaseapp.com',
    storageBucket: 'herfa-3e5ff.firebasestorage.app',
    measurementId: 'G-EEFCYFC1Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhRQnRaIxbLzkAP6R0TqjNGv_GuIciiU4',
    appId: '1:124678530522:android:6718bfc55997b0cdc04ce3',
    messagingSenderId: '124678530522',
    projectId: 'herfa-3e5ff',
    storageBucket: 'herfa-3e5ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh5nbuqxqXGOvmdIJzg7rxkgrxA9h9YA4',
    appId: '1:124678530522:ios:2462dea140449dbec04ce3',
    messagingSenderId: '124678530522',
    projectId: 'herfa-3e5ff',
    storageBucket: 'herfa-3e5ff.firebasestorage.app',
    iosBundleId: 'com.example.herfa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh5nbuqxqXGOvmdIJzg7rxkgrxA9h9YA4',
    appId: '1:124678530522:ios:2462dea140449dbec04ce3',
    messagingSenderId: '124678530522',
    projectId: 'herfa-3e5ff',
    storageBucket: 'herfa-3e5ff.firebasestorage.app',
    iosBundleId: 'com.example.herfa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZBLFJrtNGMaHQLEa0uAsD25gsO1WW0ks',
    appId: '1:124678530522:web:d6ab9a51b0caea1ac04ce3',
    messagingSenderId: '124678530522',
    projectId: 'herfa-3e5ff',
    authDomain: 'herfa-3e5ff.firebaseapp.com',
    storageBucket: 'herfa-3e5ff.firebasestorage.app',
    measurementId: 'G-G82TLKLRWL',
  );
}
